### ISSUE TITLE
.to_categorical examples don't work in the notes

### ISSUE THREAD

**Issue by amberc-github** [GavinHuttley/tib#110]
table.to_categorical isn't actually working at all for a few of us students, but seeing as this is the 3157 GitHub page just wanted to raise that the 8.8.8, 8.8.7.1, and 8.9 (including the Constructing CategoryCounts from a Table' sidebar in 8.9) usages of .to_categorical aren't clear enough (although @BrendanBeaton and I both think there may be an issue with the underlying method itself...)

**Directly from 8.8**
![help](https://user-images.githubusercontent.com/69443038/93709023-49278800-fb7e-11ea-8ff4-359b190dd4dd.PNG)

**Won't work for tables**
![whyyy](https://user-images.githubusercontent.com/69443038/93709024-4a58b500-fb7e-11ea-957f-a3a3dc9d9994.PNG)

**Comment by GavinHuttley** [comment]
Whoops! The issue is I just added that method to Table and had not propagated latest version to server. It will be there now, make sure you restart your notebook.
