### ISSUE TITLE
5.29: Working with files, possible typo, or clarification wanted

### ISSUE THREAD

**Issue by JackRicho** [GavinHuttley/tib#232]
5.29: Working with files (end of) first paragraph states:

_"  Opening a file to read does not return the files contents. "_

However, other sources online <sup>[1]</sup> state that opening a file to read returns whole text, which seem not to agree with the content of the document. If this is a misunderstanding on my part, I would appreciate if an explanation could be added that outlines what opening a file to read does, if not return the files contents.

Thanks

[1] <sup>https://www.w3schools.com/python/python_file_open.asp</sup>

**Comment by GavinHuttley** [comment]
This line in the example on the page you reference
```python
f = open("demofile.txt", "r")
```
is opening **a file to be read**, as indicated by the `"r"` argument. If you look at the variable `f` (or equivalent in another python session), it **is not** the contents of the file `demofile.txt` but an object that has a reference to that files location on disk.

The next statement in that example
```python
print(f.read())
```
**is** reading the contents of the file. Hope that helps you understand the statement in the notes!
