### ISSUE TITLE
5.33 numpy - potential for confusion

### ISSUE THREAD

**Issue by BrendanBeaton** [GavinHuttley/tib#67]
<img width="636" alt="Screen Shot 2020-08-20 at 16 34 56" src="https://user-images.githubusercontent.com/32605973/90725482-93a9b080-e303-11ea-8fe1-8541fff1bdb2.png">

There is nothing wrong here. I just worry that for someone who is struggling to understand, that the rows of m equalling 2 and then the result of m[row_index, col_index] = 2 by chance, might introduce some confusion.

**Comment by BrendanBeaton** [comment]
I can go through and change the value if you think it should be changed.

**Comment by GavinHuttley** [comment]
Ah, gotcha. Fixing now.
