### ISSUE TITLE
Setting `x` and `y` in `plotly.express.imshow` produces wrong output

### ISSUE THREAD

**Issue by J-Wall** [GavinHuttley/tib#95]
In the [https://github.com/GavinHuttley/tib/blob/develop/source/seqcomp/dotplot.rst](dotplot section), the code block
```
import plotly.express as px

fig = px.imshow(
    matches,
    range_color=[0.0, 1.0],
    x=list("AGCGT"),
    y=list("AT"),
    color_continuous_scale="gray",
)
# we want to suppress the colour scale bar
fig.update_layout(coloraxis_showscale=False)
fig.update_xaxes(showgrid=True, linewidth=2, linecolor="black", mirror=True)
fig.update_yaxes(showgrid=True, linewidth=2, linecolor="black", mirror=True)
fig.show()
```

This incorrectly produces this output image:

![newplot(8)](https://user-images.githubusercontent.com/15355329/92360783-bb38af80-f130-11ea-8627-6489a3e6580a.png)

It appears that `plotly.express.imshow` only shows unique values on the axes... I don't think this is the intended behaviour. Note that the first 5 lines of the output of `fig.to_dict()` are
```
{'data': [{'coloraxis': 'coloraxis',
   'x': ['A', 'G', 'C', 'G', 'T'],
   'y': ['A', 'T'],
   'z': array([[0, 1, 1, 1, 1],
          [1, 1, 1, 1, 0]]),
```
So the data is not lost, it is just not shown by plotly.

Simple workaround is to remove the `x` and `y` keywords, but of course this also removes the nucleotide labels. I will consider putting in an issue on the plotly github.

**Comment by GavinHuttley** [comment]
Wow, that's odd. Good catch. We can include the correct labels with the following
```python
fig.update_xaxes(
    showgrid=True,
    linewidth=2,
    linecolor="black",
    mirror=True,
    ticktext=["A", "G", "C", "G", "T"],
    tickvals=[0, 1, 2, 3, 4],
)
fig.update_yaxes(
    showgrid=True,
    linewidth=2,
    linecolor="black",
    mirror=True,
    ticktext=["A", "T"],
    tickvals=[0, 1],
)
```

I'm fixing the online notes to use this. I agree this should be posted as an issue on Plotly github page.
